version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './mariadb_data:/bitnami'

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './redis_data:/bitnami'

  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - './mongodb_data:/bitnami'

  dreamfactory:
    image: 'bitnami/dreamfactory:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '180:80'
      - '1443:443'
    depends_on:
      - mariadb
      - redis
      - mongodb
    volumes:
      - './dreamfactory_data:/bitnami'

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin:4.7.9-1
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=prout
    ports:
      - "181:80"
    depends_on:
      - mariadb
    links:
      - "mariadb:db"
