version: '2.0'
services:
  php:
    container_name: "${APP_NAME}_php"
    build: .
    restart: always
    volumes:
      - "./www:/var/www/html/api"
      - "./config/apache/sites-available:/etc/apache2/sites-available"
      - "./config/apache/sites-enabled:/etc/apache2/sites-enabled"
    working_dir: /var/www/html/api
    ports:
      - "${PORT}:80"